### ISSUE TITLE
RuntimeError: cannot unsqueeze empty tensor

### ISSUE THREAD

**Issue by Shualite** [lvpengyuan/corner#10]
`Traceback (most recent call last):
  File "eval_all.py", line 380, in <module>
    main()
  File "eval_all.py", line 347, in main
    out, seg_pred, seg_map =net(img)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/fsy_SceneTextRec/Docker-pytorch-0.3/corner-master/dssd.py", line 113, in forward
    output = self.detect(loc.view(loc.size(0), -1, 4, 4), self.softmax(conf.view(-1, self.num_classes)), self.priors, F.sigmoid(seg_view), F.sigmoid(seg_pred))
  File "/root/fsy_SceneTextRec/Docker-pytorch-0.3/corner-master/layers/functions/detection.py", line 50, in forward
    temp.append(torch.cat((scores[ids[:count]].unsqueeze(1),`

I also find that this code can only run in the pytorch environment under pytorch0.4, otherwise we need to change the c code in the roi_pooling module. 
I meet this error above when i run on pytorch0.4.1 and run the eval_all.py

**Comment by Shualite** [comment]
@lvpengyuan

**Comment by lhn217** [comment]
> @lvpengyuan

do you resolve this problem now?

**Comment by zhangchurong** [comment]
+1
