### ISSUE TITLE
File not found error.

### ISSUE THREAD

**Issue by abhishek-kumar-onometra** [lvpengyuan/corner#13]
I'm getting the following error:

  File "/home/mukut/gitlab/corner/data/icdar.py", line 49, in __init__
    ic13_samples = open(ic13_list_path, 'r').readlines()
IOError: [Errno 2] No such file or directory: '../data/ocr/detection//icdar2013/test_list.txt'

when I executed eval_all.py file.

Any suggestion.

**Comment by TonyDanidXHY** [comment]
Is your problem solved？

**Comment by tayson0825** [comment]
> I'm getting the following error:
> 
> File "/home/mukut/gitlab/corner/data/icdar.py", line 49, in **init**
> ic13_samples = open(ic13_list_path, 'r').readlines()
> IOError: [Errno 2] No such file or directory: '../data/ocr/detection//icdar2013/test_list.txt'
> 
> when I executed eval_all.py file.
> 
> Any suggestion.

Is your problem solved？

**Comment by 15926273249** [comment]
have you solved this problem?

**Comment by tayson0825** [comment]
> have you solved this problem?

yes .you should make such a .list file (similar to txt file) by yourself , each line is the file name of all test image files

**Comment by 15926273249** [comment]
Can you send me your txt files and the corresponding datasets? Thank you!

**Comment by tayson0825** [comment]
I did not test it on the icdar2013 task, I did it on COCO-Text, this data set needs to go to the official website to download the train2014 folder (https://rrc.cvc.uab.es/?ch=5&com=downloads )

And then i wrote a python script according to the file name of the test picture in the downloaded data to get the test.list file (Baidu SkyDrive: link: https://pan.baidu.com/s/1lCxm_z8HflyMdGXsKVnUHA
Extraction code: cfkp)

**Comment by 15926273249** [comment]
have you tried evaluate_msra.py.       First I tested eval_all.py on td500 dataset, then I got the outputs_eval dataset, and I set the root of detection_results_dir as '/outputs_eval/td500/240/res/' in evaluate_msra.py, but I got 
Traceback (most recent call last):
  File "evaluate_msra.py", line 153, in <module>
    recall=float(tp)/(tp+fp)
ZeroDivisionError: float division by zero
Do you know how to fix it?

**Comment by TonyDanidXHY** [comment]
Yes, I rewritten evaluate_msra.py when I executed COCO-Text. If tp+fp are all 0, it may indicate that there is a calibration frame of gt. I haven't encountered this problem temporarily

**Comment by tayson0825** [comment]
Yes, I rewritten evaluate_msra.py when I executed COCO-Text. If tp+fp is 0, it may indicate that there is no gt calibration frame. I haven't encountered this problem temporarily

**Comment by 15926273249** [comment]
can you send me your modified evaluate_msra.py ?

**Comment by tayson0825** [comment]
Ok. But I recommend that you can change it yourself to meet your requirements
(Baidu SkyDrive: link: https://pan.baidu.com/s/1cjhctYfjQ-zoz2Jwf0vLdg
Extraction code: qnhp)

**Comment by 15926273249** [comment]
have you tried testing on one image instead of the whole dataset ?
